version: "3"
services:
  postgres:
    restart: always
    image: postgres:11
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: connect
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
  webserver:
    build: ./backend
    depends_on:
      - postgres
    volumes:
      - ./backend:/backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    stdin_open: true
    entrypoint: npm run dev
